# Generated by Django 4.2.7 on 2025-11-09 10:11

from django.db import migrations
import django_resized.forms
import menu.models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', help_text='Imagen del producto (recomendado: 800x600px, formato JPG)', keep_meta=True, null=True, quality=85, scale=None, size=[800, 600], upload_to=menu.models.menu_item_image_path),
        ),
    ]
